In [ ]:
import numpy as np

In [ ]:
data1 = [[1, 2, 3, 4, 5, 10], [5, 6, 7, 8, 1, 0]]
arr1 = np.array(data1)

In [ ]:
np.arange(3)
np.arange(2, 12)
np.arange(3, 27, 3)

In [ ]:
np.random.randn(5)
np.random.randn(2, 3)

In [ ]:
arr1 = np.array([1, 2, 3], dtype = np.float32)
arr2 = np.array([1, 2, 3], dtype = "i4")

arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(type(float_arr))

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([2, 2, 1])
arr2 = np.array([1, 2, 2])

arr * arr
arr1 * arr2
arr1 + arr2
arr1 / arr2

In [ ]:
arr1 = np.array([1, 2, 3])
arr1 * 3

In [22]:
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)

[-0.57547997  0.66883304  0.61995708 -0.27979828 -0.79301176 -0.43347165]
[-0.79301176 -0.57547997 -0.43347165 -0.27979828  0.61995708  0.66883304]


In [24]:
arr = np.random.randn(5, 3)
arr.sort(axis=0)
arr

array([[-0.87028115, -1.81372564, -0.94361546],
       [ 0.58872241, -0.80744881, -0.91159834],
       [ 0.71592273,  0.77906802, -0.77722476],
       [ 0.83763193,  1.32645007, -0.21025697],
       [ 1.1608214 ,  2.04448833,  0.36264518]])

In [26]:
arr = np.array([1, 2, 2])
print(arr.sum())
print(arr.mean())


5
1.6666666666666667
