In [5]:
import numpy as np
arr = np.array([[-1,2,3], [4,10,6],[-1,2,3]])
arr.sum(1)

array([ 4, 20,  4])

In [13]:
arr = np.arange(10, 29, 2)
print(arr[3:-1])
print(arr[-7:-1])
print(arr[:-1])
print(arr[3:])

[16 18 20 22 24 26]
[16 18 20 22 24 26]
[10 12 14 16 18 20 22 24 26]
[16 18 20 22 24 26 28]


In [17]:
arr = np.array([[-1, 2, 3], [4, 10, 6]])
arr.sort(1)
arr

array([[-1,  2,  3],
       [ 4,  6, 10]])

In [18]:
arr = np.array([[-1, 2, 3], [4, 10, 6]])
arr.sort(axis=1)
arr

array([[-1,  2,  3],
       [ 4,  6, 10]])

In [19]:
arr = np.array([[-1, 2, 3], [4, 10, 6]])
arr.sort(axis=0)
arr

array([[-1,  2,  3],
       [ 4, 10,  6]])

In [20]:
arr = np.array([[-1, 2, 3], [4, 10, 6]])
arr.sort()
arr

array([[-1,  2,  3],
       [ 4,  6, 10]])